# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=3)),
                ('duration', models.CharField(max_length=10)),
                ('filesize', models.CharField(max_length=10)),
                ('download_url', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
