# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_metadata_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='video_id',
            field=models.CharField(max_length=255),
        ),
    ]
